#!/bin/bash

#executables
cp bin/rpc_request /usr/bin/network-sensor-server-rpc-client
cp bin/server /usr/bin/network-sensor-server

#config file
mkdir -p /etc/network-sensor-server
if ! test -e /etc/network-sensor-server/config.ini; then
	cp config/config.ini /etc/network-sensor-server/config.ini
fi

#add service 
cp service/network-sensor-server /etc/init.d/network-sensor-server

#create log dir
mkdir -p /var/log/network-sensor-server