#!/bin/bash
#
# chkconfig: 35 90 12
# description: Foo server
#
# Get function from functions library
# Start the service FOO
SEREXE=/usr/bin/network-sensor-server
SERPID=/var/run/network-sensor-server.pid
SCHEXE=/usr/bin/scheduler
SCHPID=/var/run/network-sensor-scheduler.pid
CONF=/etc/network-sensor-server/config.ini

if ! test -e $EXE; then
	echo "No executable"
	exit 1
fi

. /lib/lsb/init-functions

start() {
	if test -e $SERPID; then
        echo "Instance already running: "
		cat $SERPID
        cat $SCHPID
		exit 1
    fi

    echo "Starting server: "
    if ! start-stop-daemon --start --quiet --oknodo -m -p $SERPID --exec $SEREXE -- -D; then
		log_end_msg 1
        exit 1
    fi
    cat $SERPID

    echo "Starting scheduler: "
    if ! start-stop-daemon --start --quiet --oknodo -m -p $SCHPID --exec $SCHEXE -- -D; then
        log_end_msg 1
        exit 1
    fi
    cat $SCHPID

    echo "Starting iperf servers"
	source $CONF 2> /dev/null 
	iperf -s -p $tcp_iperf_port > /var/log/network-sensor-server/tcp_iperf_log &
	iperf -s -u -p $udp_iperf_port > /var/log/network-sensor-server/udp_iperf_log &
    log_end_msg 0
	exit 0      
}
# Restart the service FOO
stop() {
    rm $SERPID
    rm $SCHPID

    echo "Stopping iperf servers"
    pkill iperf

    echo "Stopping scheduler"
    pkill -SIGTERM scheduler

    echo "Stopping server"
    pkill -SIGTERM sensor	#also kills self
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        if test -e $SERPID; then
		echo -n "Running:"
		cat $SERPID
		exit 1
	fi
	echo "No instance running"
	exit 0
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
