#!/bin/bash
#
# chkconfig: 35 90 12
# description: Foo server
#
# Get function from functions library
# Start the service FOO
SEREXE=/usr/bin/weperf-server
SERPID=/var/run/weperf-server.pid
SCHEXE=/usr/bin/weperf
SCHPID=/var/run/weperf-scheduler.pid
NOTEXE=/usr/bin/weperf-notifier
NOTPID=/var/run/weperf-notifier.pid
SENEXE=/usr/bin/weperf-sensor
SENPID=/var/run/weperf-sensor.pid
CONF=/etc/weperf/server-config.ini

if ! test -e $EXE; then
	echo "No executable"
	exit 1
fi

. /lib/lsb/init-functions

start() {
	if test -e $SERPID; then
        echo "Instance already running: "
		cat $SERPID
        cat $SCHPID
		exit 1
    fi

    echo "Starting server: "
    if ! start-stop-daemon --start --quiet --oknodo -m -p $SERPID --exec $SEREXE -- -D; then
		log_end_msg 1
        exit 1
    fi
    cat $SERPID

    echo "Starting scheduler: "
    if ! start-stop-daemon --start --quiet --oknodo -m -p $SCHPID --exec $SCHEXE -- -D; then
        log_end_msg 1
        exit 1
    fi
    cat $SCHPID

    # Only if sensor is installed
    if test -e $SENEXE; then
        echo "Starting sensor: "
        $SENEXE > /dev/null &
        printf $! > $SENPID
        cat $SENPID

        echo "Starting iperf servers: "
        iperf -s -p 5001 > /var/log/weperf/iperf/tcp_log &
        echo $!
        iperf -s -u -p 5002 > /var/log/weperf/iperf/udp_log &
        echo $!
    fi

    log_end_msg 0
	exit 0      
}
# Restart the service FOO
stop() {
    rm $SERPID
    rm $SCHPID

    echo "Stopping sensor"
    kill $(cat $SENPID)

    rm $SENPID

    echo "Stopping iperf servers"
    pkill iperf

    echo "Stopping weperf scheduler"
    pkill -SIGTERM weperf-scheduler

    echo "Stopping weperf server"
    pkill -SIGTERM weperf-server	#also kills self
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        if test -e $SERPID; then
		echo -n "Running:"
		cat $SERPID
		exit 1
	fi
	echo "No instance running"
	exit 0
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
